package ventanas;

/**
 *
 * @author Walter
 */
public class FrmGestionInfografia extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionInfografia
     */
    public FrmGestionInfografia() {
        initComponents();
        setTitle("Gestion de Infografia");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnAgregar22 = new javax.swing.JButton();
        btnAgregar23 = new javax.swing.JButton();
        btnAgregar24 = new javax.swing.JButton();
        btnAgregar25 = new javax.swing.JButton();
        btnAgregar26 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnAgregar17 = new javax.swing.JButton();
        btnAgregar18 = new javax.swing.JButton();
        btnAgregar19 = new javax.swing.JButton();
        btnAgregar20 = new javax.swing.JButton();
        btnAgregar21 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnAgregar12 = new javax.swing.JButton();
        btnAgregar13 = new javax.swing.JButton();
        btnAgregar14 = new javax.swing.JButton();
        btnAgregar15 = new javax.swing.JButton();
        btnAgregar16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 280));
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(550, 320));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese Autor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 20, 170, 21);

        jTextField2.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 50, 320, 31);

        btnAgregar22.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar22.setText("GUARDAR");
        btnAgregar22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar22.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar22.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar22ActionPerformed(evt);
            }
        });

        btnAgregar23.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar23.setText("SALIR");
        btnAgregar23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar23.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar23.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar23ActionPerformed(evt);
            }
        });

        btnAgregar24.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar24.setText("ELIMINAR");
        btnAgregar24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar24.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar24.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar24ActionPerformed(evt);
            }
        });

        btnAgregar25.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar25.setText("AGREGAR");
        btnAgregar25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar25.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar25.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar25ActionPerformed(evt);
            }
        });

        btnAgregar26.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar26.setText("EDITAR");
        btnAgregar26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar26.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar26.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar25, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel11);
        jPanel11.setBounds(10, 130, 523, 60);

        jTabbedPane1.addTab("Autor", jPanel1);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese Editorial");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 20, 170, 21);

        jTextField3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel2.add(jTextField3);
        jTextField3.setBounds(30, 50, 320, 31);

        btnAgregar17.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar17.setText("GUARDAR");
        btnAgregar17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar17.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar17.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar17ActionPerformed(evt);
            }
        });

        btnAgregar18.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar18.setText("SALIR");
        btnAgregar18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar18.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar18.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar18ActionPerformed(evt);
            }
        });

        btnAgregar19.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar19.setText("ELIMINAR");
        btnAgregar19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar19.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar19.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar19ActionPerformed(evt);
            }
        });

        btnAgregar20.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar20.setText("AGREGAR");
        btnAgregar20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar20.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar20.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar20ActionPerformed(evt);
            }
        });

        btnAgregar21.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar21.setText("EDITAR");
        btnAgregar21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar21.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar21.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2.add(jPanel10);
        jPanel10.setBounds(10, 130, 523, 60);

        jTabbedPane1.addTab("Editorial", jPanel2);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel5.setText("Ingrese Genero");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 20, 170, 21);

        jTextField4.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel3.add(jTextField4);
        jTextField4.setBounds(30, 50, 320, 31);

        btnAgregar12.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar12.setText("GUARDAR");
        btnAgregar12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar12.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar12.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar12ActionPerformed(evt);
            }
        });

        btnAgregar13.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar13.setText("SALIR");
        btnAgregar13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar13.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar13.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar13ActionPerformed(evt);
            }
        });

        btnAgregar14.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar14.setText("ELIMINAR");
        btnAgregar14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar14.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar14.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar14ActionPerformed(evt);
            }
        });

        btnAgregar15.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar15.setText("AGREGAR");
        btnAgregar15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar15.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar15.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar15ActionPerformed(evt);
            }
        });

        btnAgregar16.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar16.setText("EDITAR");
        btnAgregar16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar16.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar16.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 130, 523, 60);

        jTabbedPane1.addTab("Genero", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 520, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar12ActionPerformed

    private void btnAgregar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar13ActionPerformed
        dispose();
    }//GEN-LAST:event_btnAgregar13ActionPerformed

    private void btnAgregar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar14ActionPerformed

    private void btnAgregar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar15ActionPerformed

    private void btnAgregar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar16ActionPerformed

    private void btnAgregar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar17ActionPerformed

    private void btnAgregar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar18ActionPerformed

    private void btnAgregar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar19ActionPerformed

    private void btnAgregar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar20ActionPerformed

    private void btnAgregar21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar21ActionPerformed

    private void btnAgregar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar22ActionPerformed

    private void btnAgregar23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar23ActionPerformed

    private void btnAgregar24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar24ActionPerformed

    private void btnAgregar25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar25ActionPerformed

    private void btnAgregar26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionInfografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionInfografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionInfografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionInfografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionInfografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar12;
    private javax.swing.JButton btnAgregar13;
    private javax.swing.JButton btnAgregar14;
    private javax.swing.JButton btnAgregar15;
    private javax.swing.JButton btnAgregar16;
    private javax.swing.JButton btnAgregar17;
    private javax.swing.JButton btnAgregar18;
    private javax.swing.JButton btnAgregar19;
    private javax.swing.JButton btnAgregar20;
    private javax.swing.JButton btnAgregar21;
    private javax.swing.JButton btnAgregar22;
    private javax.swing.JButton btnAgregar23;
    private javax.swing.JButton btnAgregar24;
    private javax.swing.JButton btnAgregar25;
    private javax.swing.JButton btnAgregar26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
