package ventanas;


/**
 *
 * @author Walter
 */
public class FrmGestionReferenciales extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionReferenciales
     */
    public FrmGestionReferenciales() {
        initComponents();
        setTitle("Gestion de Referenciales");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnAgregar2 = new javax.swing.JButton();
        btnAgregar3 = new javax.swing.JButton();
        btnAgregar4 = new javax.swing.JButton();
        btnAgregar5 = new javax.swing.JButton();
        btnAgregar6 = new javax.swing.JButton();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblPais1 = new javax.swing.JLabel();
        txtPais1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnAgregar7 = new javax.swing.JButton();
        btnAgregar8 = new javax.swing.JButton();
        btnAgregar9 = new javax.swing.JButton();
        btnAgregar10 = new javax.swing.JButton();
        btnAgregar11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnAgregar12 = new javax.swing.JButton();
        btnAgregar13 = new javax.swing.JButton();
        btnAgregar14 = new javax.swing.JButton();
        btnAgregar15 = new javax.swing.JButton();
        btnAgregar16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 280));

        jTabbedPane1.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        btnAgregar2.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar2.setText("GUARDAR");
        btnAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar2.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar2.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnAgregar3.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar3.setText("SALIR");
        btnAgregar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar3.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar3.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        btnAgregar4.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar4.setText("ELIMINAR");
        btnAgregar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar4.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar4.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar4ActionPerformed(evt);
            }
        });

        btnAgregar5.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar5.setText("AGREGAR");
        btnAgregar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar5.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar5.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar5ActionPerformed(evt);
            }
        });

        btnAgregar6.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar6.setText("EDITAR");
        btnAgregar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar6.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar6.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 130, 523, 60);

        lblPais.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        lblPais.setText("Ingrese Pais");
        jPanel1.add(lblPais);
        lblPais.setBounds(40, 20, 93, 21);

        txtPais.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel1.add(txtPais);
        txtPais.setBounds(30, 50, 250, 31);

        jTabbedPane1.addTab("País", jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(550, 300));
        jPanel2.setLayout(null);

        lblPais1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        lblPais1.setText("Ingrese Ciudad");
        jPanel2.add(lblPais1);
        lblPais1.setBounds(40, 20, 120, 21);

        txtPais1.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel2.add(txtPais1);
        txtPais1.setBounds(30, 50, 250, 31);

        btnAgregar7.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar7.setText("GUARDAR");
        btnAgregar7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar7.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar7.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar7ActionPerformed(evt);
            }
        });

        btnAgregar8.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar8.setText("SALIR");
        btnAgregar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar8.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar8.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar8ActionPerformed(evt);
            }
        });

        btnAgregar9.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar9.setText("ELIMINAR");
        btnAgregar9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar9.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar9.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar9ActionPerformed(evt);
            }
        });

        btnAgregar10.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar10.setText("AGREGAR");
        btnAgregar10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar10.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar10.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar10ActionPerformed(evt);
            }
        });

        btnAgregar11.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar11.setText("EDITAR");
        btnAgregar11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar11.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar11.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 130, 523, 60);

        jTabbedPane1.addTab("Ciudad", jPanel2);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese Barrio");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(40, 20, 170, 21);

        jTextField2.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jPanel3.add(jTextField2);
        jTextField2.setBounds(30, 50, 320, 31);

        btnAgregar12.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar12.setText("GUARDAR");
        btnAgregar12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar12.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar12.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar12ActionPerformed(evt);
            }
        });

        btnAgregar13.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar13.setText("SALIR");
        btnAgregar13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar13.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar13.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar13ActionPerformed(evt);
            }
        });

        btnAgregar14.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar14.setText("ELIMINAR");
        btnAgregar14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar14.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar14.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar14ActionPerformed(evt);
            }
        });

        btnAgregar15.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar15.setText("AGREGAR");
        btnAgregar15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar15.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar15.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar15ActionPerformed(evt);
            }
        });

        btnAgregar16.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        btnAgregar16.setText("EDITAR");
        btnAgregar16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar16.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAgregar16.setMinimumSize(new java.awt.Dimension(100, 100));
        btnAgregar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnAgregar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 130, 523, 60);

        jTabbedPane1.addTab("Barrio", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed

    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar4ActionPerformed

    private void btnAgregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar5ActionPerformed

    private void btnAgregar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar6ActionPerformed

    private void btnAgregar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar7ActionPerformed

    private void btnAgregar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar8ActionPerformed

    private void btnAgregar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar9ActionPerformed

    private void btnAgregar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar10ActionPerformed

    private void btnAgregar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar11ActionPerformed

    private void btnAgregar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar12ActionPerformed

    private void btnAgregar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar13ActionPerformed

    private void btnAgregar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar14ActionPerformed

    private void btnAgregar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar15ActionPerformed

    private void btnAgregar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionReferenciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar10;
    private javax.swing.JButton btnAgregar11;
    private javax.swing.JButton btnAgregar12;
    private javax.swing.JButton btnAgregar13;
    private javax.swing.JButton btnAgregar14;
    private javax.swing.JButton btnAgregar15;
    private javax.swing.JButton btnAgregar16;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnAgregar5;
    private javax.swing.JButton btnAgregar6;
    private javax.swing.JButton btnAgregar7;
    private javax.swing.JButton btnAgregar8;
    private javax.swing.JButton btnAgregar9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPais1;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPais1;
    // End of variables declaration//GEN-END:variables
}
