/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ventanas;

import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;



/**
 *
 * @author caches
 */
public class FrmMdi extends javax.swing.JFrame {

    /**
     * Creates new form FrmMdi
     */
    public FrmMdi() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setResizable(false);
        this.
        
        pnlGestionLibros.setVisible(false);
        pnlGestionUbicaciones.setVisible(false);
        pnlGestionPersonas.setVisible(false);
        
//        frmMenu frmMenu = new frmMenu();
//        desktopPane.add(frmMenu);
//        frmMenu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGestionPersona = new javax.swing.JButton();
        btnGestionLibros = new javax.swing.JButton();
        btnGestionUbicacion = new javax.swing.JButton();
        btnRegistrarLibros = new javax.swing.JButton();
        btnRegistrarAlquiler = new javax.swing.JButton();
        pnlGestionUbicaciones = new javax.swing.JPanel();
        btnBarrio = new javax.swing.JButton();
        btnCiudad = new javax.swing.JButton();
        btnPais = new javax.swing.JButton();
        pnlGestionLibros = new javax.swing.JPanel();
        btnGeneros = new javax.swing.JButton();
        btnEditoriales = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        pnlGestionPersonas = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblLogo.setIcon(new javax.swing.ImageIcon("/home/caches/Documents/UTIC/LPT1/FINALJAVA/src/assets/logo.png")); // NOI18N
        lblLogo.setText("jLabel2");
        desktopPane.add(lblLogo);
        lblLogo.setBounds(0, 0, 260, 240);
        desktopPane.add(jSeparator1);
        jSeparator1.setBounds(10, 470, 240, 20);

        btnGestionPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnGestionPersona.setText("Gestion personas");
        btnGestionPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPersonaActionPerformed(evt);
            }
        });
        desktopPane.add(btnGestionPersona);
        btnGestionPersona.setBounds(10, 410, 240, 50);

        btnGestionLibros.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnGestionLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnGestionLibros.setText("Gestion de libros");
        btnGestionLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLibrosActionPerformed(evt);
            }
        });
        desktopPane.add(btnGestionLibros);
        btnGestionLibros.setBounds(10, 370, 240, 50);

        btnGestionUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnGestionUbicacion.setText("Gestión de Ubicaciones");
        btnGestionUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUbicacionActionPerformed(evt);
            }
        });
        desktopPane.add(btnGestionUbicacion);
        btnGestionUbicacion.setBounds(10, 330, 240, 50);

        btnRegistrarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnRegistrarLibros.setText("Registrar libros");
        btnRegistrarLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desktopPane.add(btnRegistrarLibros);
        btnRegistrarLibros.setBounds(10, 290, 240, 50);

        btnRegistrarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnRegistrarAlquiler.setText("Registrar alquiler");
        btnRegistrarAlquiler.setAutoscrolls(true);
        btnRegistrarAlquiler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desktopPane.add(btnRegistrarAlquiler);
        btnRegistrarAlquiler.setBounds(10, 250, 240, 50);

        pnlGestionUbicaciones.setLayout(null);

        btnBarrio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnBarrio.setText("Gestionar Barrio");
        btnBarrio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionUbicaciones.add(btnBarrio);
        btnBarrio.setBounds(0, 80, 240, 50);

        btnCiudad.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnCiudad.setText("Gestionar Ciudad");
        btnCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionUbicaciones.add(btnCiudad);
        btnCiudad.setBounds(0, 40, 240, 50);

        btnPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnPais.setText("Gestionar Pais");
        btnPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionUbicaciones.add(btnPais);
        btnPais.setBounds(0, 0, 240, 50);

        desktopPane.add(pnlGestionUbicaciones);
        pnlGestionUbicaciones.setBounds(10, 480, 240, 130);

        pnlGestionLibros.setLayout(null);

        btnGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnGeneros.setText("Gestionar Generos");
        btnGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionLibros.add(btnGeneros);
        btnGeneros.setBounds(0, 80, 240, 50);

        btnEditoriales.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnEditoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnEditoriales.setText("Gestionar Editoriales");
        btnEditoriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionLibros.add(btnEditoriales);
        btnEditoriales.setBounds(0, 40, 240, 50);

        btnAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnAutores.setText("Gestionar Autores");
        btnAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionLibros.add(btnAutores);
        btnAutores.setBounds(0, 0, 240, 50);

        desktopPane.add(pnlGestionLibros);
        pnlGestionLibros.setBounds(10, 480, 240, 130);

        pnlGestionPersonas.setLayout(null);

        btnCliente.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnCliente.setText("Gestionar Cliente");
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionPersonas.add(btnCliente);
        btnCliente.setBounds(0, 40, 240, 50);

        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/add.png"))); // NOI18N
        btnPersonal.setText("Gestionar Personal");
        btnPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGestionPersonas.add(btnPersonal);
        btnPersonal.setBounds(0, 0, 240, 50);

        desktopPane.add(pnlGestionPersonas);
        pnlGestionPersonas.setBounds(10, 480, 240, 90);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        desktopPane.add(btnSalir);
        btnSalir.setBounds(10, 620, 240, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPersonaActionPerformed
        elegirMenuDinamico("pnlGestionPersonas");
    }//GEN-LAST:event_btnGestionPersonaActionPerformed

    private void btnGestionUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUbicacionActionPerformed
        elegirMenuDinamico("pnlGestionUbicaciones");
    }//GEN-LAST:event_btnGestionUbicacionActionPerformed

    private void btnGestionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLibrosActionPerformed
        elegirMenuDinamico("pnlGestionLibros");
    }//GEN-LAST:event_btnGestionLibrosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0); // Cerrar la JVM con return 0
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void elegirMenuDinamico(String opcion){
        switch (opcion) {
            case "pnlGestionUbicaciones":
                // Desactivamos paneles
                pnlGestionLibros.setVisible(false);
                pnlGestionPersonas.setVisible(false);
                
                // Activamos panel correcto y repintamos
                pnlGestionUbicaciones.setVisible(true);
                pnlGestionUbicaciones.repaint();
                break;
            case "pnlGestionLibros":
                pnlGestionUbicaciones.setVisible(false);
                pnlGestionPersonas.setVisible(false);
                
                pnlGestionLibros.setVisible(true);
                pnlGestionLibros.repaint();
                break;
            case "pnlGestionPersonas":
                pnlGestionLibros.setVisible(false);
                pnlGestionUbicaciones.setVisible(false);
                
                pnlGestionPersonas.setVisible(true);
                pnlGestionPersonas.repaint();
                break;
            default:
                throw new AssertionError();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatCarbonIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMdi().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnBarrio;
    private javax.swing.JButton btnCiudad;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditoriales;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnGestionLibros;
    private javax.swing.JButton btnGestionPersona;
    private javax.swing.JButton btnGestionUbicacion;
    private javax.swing.JButton btnPais;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnRegistrarAlquiler;
    private javax.swing.JButton btnRegistrarLibros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlGestionLibros;
    private javax.swing.JPanel pnlGestionPersonas;
    private javax.swing.JPanel pnlGestionUbicaciones;
    // End of variables declaration//GEN-END:variables

}
